// Vercel Serverless Function: GET /api/lp?c=<slug>
//
// Serves a hosted client landing page generated by /api/render-landing.
// Reads the stored HTML from the Supabase `landing_pages` table and returns it
// as a real web page. This is the public-facing URL clients open.

const { createClient } = require("@supabase/supabase-js");

let _sb = null;
function getSb() {
  if (_sb) return _sb;
  const url = process.env.SUPABASE_URL;
  const key = process.env.SUPABASE_SERVICE_KEY || process.env.SUPABASE_SERVICE_ROLE_KEY;
  if (!url || !key) throw new Error("Missing SUPABASE env vars");
  _sb = createClient(url, key, { auth: { persistSession: false } });
  return _sb;
}

module.exports = async (req, res) => {
  try {
    const slug = (req.query && req.query.c) || "";
    if (!slug) {
      res.setHeader("Content-Type", "text/html; charset=utf-8");
      return res.status(400).send("<h1>Missing page id</h1>");
    }

    const sb = getSb();
    const { data, error } = await sb
      .from("landing_pages")
      .select("html")
      .eq("slug", slug)
      .single();

    if (error || !data) {
      res.setHeader("Content-Type", "text/html; charset=utf-8");
      return res.status(404).send("<h1>Page not found</h1>");
    }

    res.setHeader("Content-Type", "text/html; charset=utf-8");
    res.setHeader("Cache-Control", "public, max-age=300");
    return res.status(200).send(data.html);
  } catch (err) {
    console.error("lp serve error:", err);
    res.setHeader("Content-Type", "text/html; charset=utf-8");
    return res.status(500).send("<h1>Something went wrong</h1>");
  }
};
